### ISSUE TITLE
Eureka Client 공통 작업

### ISSUE THREAD

**Issue by linho1150** [Backble/popool#118]
## 목적
Eureka Client 작업 총 두가지 File에 데이터를 추가해야합니다!
1. application.yml
```
spring:
  application:
    name: bbl-모듈명

eureka:
  instance:
    hostname: bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
```
2. build.gradle
```
ext {
    set('springCloudVersion', "2021.0.3")
}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
dependencies {
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
}
```
⭐dependencies는 기존에 있던거에 추가만해주세요

**Comment by sienna011022** [comment]
첨언하자면 자기 서비스에 유레카 클라이언트 어노테이션도 달아야 합니다!
예시는 다음과 같습니다.
```
@EnableEurekaClient

public class BblCareerApplication {

	public static void main(String[] args) {
		SpringApplication.run(BblCareerApplication.class, args);
	}

}
```

**Comment by sienna011022** [comment]
application.yml에 관해 제안 하나 드립니다.
중간에 다음 코드를 추가하면 유레카와 서비스 간 정보를 가져오는 시간을 줄일 수 있다고 합니다! 넣는 것이 어떤가요?

```
    registryFetchIntervalSeconds: 5
    disable-delta: true
```

적용 코드

```
eureka:
  instance:
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    disable-delta: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
```
