### ISSUE TITLE
Eureka Client 설정 - career

### ISSUE THREAD

**Issue by sienna011022** [Backble/popool#126]
## 목적
> Eureka Client 설정
## 작업 상세 내용
- [x] client(bbl-career)등록
```
eureka:
  instance:
    hostname: bbleureka-env.eba-sk7czfia.ap-northeast-2.elasticbeanstalk.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
```
## 참고 사항
local에서 작업하여 그런지 스프링은 동작 하나 api를 던지면 서버를 찾지 못하는 오류가 나긴 함.
