### ISSUE TITLE
Eureka Client 코드 구성 및 설정

### ISSUE THREAD

**Issue by linho1150** [Backble/popool#71]
## 목적
> Eureka Client 생성에 필요한 어노테이션, application.yml 파일 등 기본적으로 갖춰야할 내용을 구성한다.
## 작업 상세 내용
- [x] 필요한 annotation 명세
- [x] 필요한 dependencies 명세
- [x] 필요한 application.yml 명세
### Dependencies 명세
```
dependencies {
     implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:3.1.3'
}
```
netflix-eureka-client dependence 추가
### Annotation 명세
```
@SpringBootApplication
@EnableDiscoveryClient
public class DiscoveryApplication {
    public static void main(String[] args) {
        SpringApplication.run(DiscoveryApplication.class, args);
    }
}
```
SpringBootApplication 아래 EnableDiscoveryClient 어노테이션 추가
### application.yml 명세
```
spring:
  application:
    name: bbl-모듈명

eureka:
  instance:
    hostname: eureka-env.eba-nih94evk.ap-northeast-2.elasticbeanstalk.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}/eureka/
```
spring.application.name 항목을 본인의 모듈명으로 변경
